# Generated by Django 3.0.5 on 2020-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('main', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('youtube_link', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
