# Generated by Django 2.2.6 on 2020-04-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200409_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cluster',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
